sudo: false
language: ruby
cache: bundler
env:
  matrix:
  - BUNDLE_PATH=.bundle
  global:
    secure: kbi3SpJLZWofR2azIHsVOaQdEa+GwsDJNztSf741aS8NwwSACsDlcVTgoAEnmNysOO7o5WfE8QM+6kNFTF77pBzhpxJ9GbK7LTx/Nwu5oqbprU0V/yWNnPlVj2iCTw2NI7UnjwLhf38zpKDYNqDpL9sBv3YrJY0sEu+yBTF+oagQsVKHSxmKnCxlPQo41CPhkzfKA7yQllQWy15wmqcfOuNAfBQK80fkYA1VOkLroy9h2U16a/Nzttbxg3F1b4TZ+qOyMXWYqdSt7CoMl3VFunn2pcFMgmEQEQY+95+VhvYOS1uWojwIUjzjUFABC1jv06KyFMyCh1Jv1tJ4BYxsd9OuyvDcZdSbNfnU1VRj51fOHcAWh3mTHYJ4GoICBlG9aohjLDgHaHvl11pW6Uc+Gj5N6qo3PYG2Vvaur/1nww4tJoWkhLKv5EZSc4+SJLxjPaPDmsQRqHWaa8iuaI4GiwIWfxKtW+R0NgAjdzhNMBHti2jAS5ldlEpT+OPN/NzJAlbpbjTH9MwxpAiF08YZ/qOn8kjvCa6vGm4IT0E2s9cNdX5r4gcDOGiXmIDp+v2PIo73sWsmaQOQkluUViAzm4d8+rOr94oWacS9WBTpMZQhCmn8uRyWa3zpdEmvCb4cHjVDDaCDZfgmEZuZNyd0js6A3CfoQh/z1qdg+s5AZb8=
script: ./script/cibuild
gemfile: this/does/not/exist
rvm:
- 1.9.3
- 2.0.0
- 2.1.2
